name: Dawn
version: 1.0
api-version: 1.16
main: me.clawifier.Dawn.Main
authors: [Clawifier]
description: Permissions system.

commands:
  perms:
    description: Modify/view rank permissions.
  ranks:
    description: Execute rank actions.